import { CommunityPost, Comment, User } from './types';
import { mockUser, mockCommunities } from './mock-data';

// Generate mock users with varying fandom scores
const generateUsers = (): User[] => {
    const names = [
        'Jake Morrison', 'Emma Watson', 'Liam Chen', 'Sofia Rodriguez', 'Marcus Johnson',
        'Aria Patel', 'Noah Kim', 'Isabella Young', 'Ethan Wright', 'Mia Thompson',
        'Oliver Davis', 'Ava Martinez', 'William Brown', 'Sophia Lee', 'James Wilson',
        'Charlotte Anderson', 'Benjamin Taylor', 'Amelia Garcia', 'Lucas Miller', 'Harper Jones'
    ];

    return names.map((name, i) => ({
        ...mockUser,
        id: `user-${i + 10}`,
        name,
        email: `${name.toLowerCase().replace(' ', '.')}@email.com`,
        avatar: `https://api.dicebear.com/7.x/avataaars/svg?seed=${name}`,
        fandomScore: Math.floor(Math.random() * 100),
        eventsAttended: Math.floor(Math.random() * 20),
        vouchesReceived: Math.floor(Math.random() * 10),
        vouchesGiven: Math.floor(Math.random() * 8),
    }));
};

const mockUsers = generateUsers();

// Generate mock posts
export const mockPosts: CommunityPost[] = [
    // Community 1: The Midnight (community-1)
    {
        id: 'post-101',
        communityId: 'community-1',
        authorId: 'user-1',
        author: { ...mockUser, fandomScore: 92 },
        title: 'Just got my MSG tickets! Who else is going?',
        content: 'Finally managed to score VIP tickets for the Madison Square Garden show! This will be my 8th Midnight concert. The anticipation is unreal - especially hoping they play "Sunset" since it\'s been trending in the community poll.',
        type: 'discussion',
        upvotes: 234,
        downvotes: 12,
        commentCount: 67,
        isPinned: false,
        createdAt: new Date('2026-01-14T10:30:00'),
        updatedAt: new Date('2026-01-14T10:30:00'),
    },
    {
        id: 'post-102',
        communityId: 'community-1',
        authorId: 'user-11',
        author: mockUsers[1],
        title: 'My collection from every show I\'ve attended 🎸',
        content: 'Been following The Midnight since 2019. Here\'s my merch collection from all 12 shows!',
        type: 'photo',
        images: [
            'https://images.unsplash.com/photo-1619983081563-430f63602796?w=600',
            'https://images.unsplash.com/photo-1614680376573-df3480f0c6ff?w=600',
        ],
        upvotes: 567,
        downvotes: 8,
        commentCount: 89,
        isPinned: true,
        createdAt: new Date('2026-01-13T15:20:00'),
        updatedAt: new Date('2026-01-13T15:20:00'),
    },
    {
        id: 'post-103',
        communityId: 'community-1',
        authorId: 'user-12',
        author: { ...mockUsers[2], fandomScore: 45 },
        title: 'Question: Best songs to introduce someone to The Midnight?',
        content: 'My friend wants to get into synthwave and I\'m trying to create the perfect intro playlist. What are your must-have tracks? I\'m thinking Gloria, Sunset, and Days of Thunder but open to suggestions!',
        type: 'question',
        upvotes: 156,
        downvotes: 3,
        commentCount: 45,
        isPinned: false,
        createdAt: new Date('2026-01-14T08:15:00'),
        updatedAt: new Date('2026-01-14T08:15:00'),
    },
    {
        id: 'post-104',
        communityId: 'community-1',
        authorId: 'user-13',
        author: { ...mockUsers[3], fandomScore: 78 },
        title: '🚨 New single dropping next Friday!',
        content: 'Just confirmed on their Instagram - new single announcement coming next week! The teaser sounds absolutely incredible. Based on the 10-second clip, it gives major "Endless Summer" vibes.',
        type: 'news',
        upvotes: 892,
        downvotes: 5,
        commentCount: 234,
        isPinned: true,
        createdAt: new Date('2026-01-14T12:00:00'),
        updatedAt: new Date('2026-01-14T12:00:00'),
    },
    {
        id: 'post-105',
        communityId: 'community-1',
        authorId: 'user-14',
        author: { ...mockUsers[4], fandomScore: 18 },
        title: 'First concert experience - what to expect?',
        content: 'Never been to a Midnight show before. Got tickets for the Chicago date. Any tips for a first-timer? What time should I arrive? Is the merch line crazy?',
        type: 'question',
        upvotes: 89,
        downvotes: 2,
        commentCount: 56,
        isPinned: false,
        createdAt: new Date('2026-01-13T20:45:00'),
        updatedAt: new Date('2026-01-13T20:45:00'),
    },
    // Community 2: Taylor Swift (community-2)
    {
        id: 'post-201',
        communityId: 'community-2',
        authorId: 'user-15',
        author: { ...mockUsers[5], fandomScore: 97 },
        title: 'Eras Tour was absolutely life-changing',
        content: 'Just got back from my 5th Eras Tour show and I still can\'t believe the energy. Taylor played for 3.5 hours straight! The Tortured Poets section was even more emotional in person.',
        type: 'discussion',
        upvotes: 1234,
        downvotes: 23,
        commentCount: 345,
        isPinned: false,
        createdAt: new Date('2026-01-14T09:00:00'),
        updatedAt: new Date('2026-01-14T09:00:00'),
    },
    {
        id: 'post-202',
        communityId: 'community-2',
        authorId: 'user-16',
        author: { ...mockUsers[6], fandomScore: 65 },
        title: 'Friendship bracelet trading thread! 💕',
        content: 'Starting a thread for bracelet trading at the upcoming shows. Post what you\'re making and what you\'re looking for! I\'ve got "Cruel Summer", "22", and "Lavender Haze" ready.',
        type: 'discussion',
        upvotes: 567,
        downvotes: 8,
        commentCount: 189,
        isPinned: true,
        createdAt: new Date('2026-01-12T14:30:00'),
        updatedAt: new Date('2026-01-12T14:30:00'),
    },
    {
        id: 'post-203',
        communityId: 'community-2',
        authorId: 'user-17',
        author: { ...mockUsers[7], fandomScore: 33 },
        title: 'Best outfit ideas for the show?',
        content: 'First time going to a Taylor show! What era should I dress as? Thinking Reputation but Folklore also seems popular.',
        type: 'question',
        upvotes: 234,
        downvotes: 5,
        commentCount: 78,
        isPinned: false,
        createdAt: new Date('2026-01-13T11:20:00'),
        updatedAt: new Date('2026-01-13T11:20:00'),
    },
    // More diverse posts
    {
        id: 'post-301',
        communityId: 'community-1',
        authorId: 'user-18',
        author: { ...mockUsers[8], fandomScore: 88 },
        title: 'The Midnight saved my life during lockdown',
        content: 'Not to be dramatic but discovering this band in 2020 genuinely helped me get through some of the darkest times. "Light Years" on repeat hit different when you couldn\'t see anyone. Anyone else have similar stories?',
        type: 'discussion',
        upvotes: 456,
        downvotes: 4,
        commentCount: 123,
        isPinned: false,
        createdAt: new Date('2026-01-12T16:00:00'),
        updatedAt: new Date('2026-01-12T16:00:00'),
    },
    {
        id: 'post-302',
        communityId: 'community-1',
        authorId: 'user-19',
        author: { ...mockUsers[9], fandomScore: 72 },
        title: 'Fan-made music video I created for "Sunset"',
        content: 'Spent 3 months creating this synthwave-inspired music video. Used footage from 80s movies blended with original animations. Would love your feedback!',
        type: 'photo',
        images: ['https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=600'],
        upvotes: 789,
        downvotes: 12,
        commentCount: 156,
        isPinned: false,
        createdAt: new Date('2026-01-11T19:30:00'),
        updatedAt: new Date('2026-01-11T19:30:00'),
    },
];

// Mock comments with nesting
export const mockComments: Comment[] = [
    {
        id: 'comment-1',
        postId: 'post-101',
        authorId: 'user-11',
        author: { ...mockUsers[1], fandomScore: 85 },
        content: 'See you there! I\'m also VIP. Maybe we can organize a pre-show meetup?',
        upvotes: 45,
        downvotes: 1,
        depth: 0,
        replies: [
            {
                id: 'comment-1-1',
                postId: 'post-101',
                authorId: 'user-12',
                author: { ...mockUsers[2], fandomScore: 62 },
                content: 'Count me in! There\'s a great bar called Synthwave Lounge nearby.',
                upvotes: 23,
                downvotes: 0,
                parentId: 'comment-1',
                depth: 1,
                replies: [
                    {
                        id: 'comment-1-1-1',
                        postId: 'post-101',
                        authorId: 'user-1',
                        author: { ...mockUser, fandomScore: 92 },
                        content: 'Perfect! Let\'s make this happen. I\'ll create a Discord event!',
                        upvotes: 18,
                        downvotes: 0,
                        parentId: 'comment-1-1',
                        depth: 2,
                        replies: [],
                        createdAt: new Date('2026-01-14T11:30:00'),
                    },
                ],
                createdAt: new Date('2026-01-14T11:15:00'),
            },
        ],
        createdAt: new Date('2026-01-14T11:00:00'),
    },
    {
        id: 'comment-2',
        postId: 'post-101',
        authorId: 'user-15',
        author: { ...mockUsers[5], fandomScore: 97 },
        content: 'This will be my 15th Midnight show! The MSG venue is incredible for their sound.',
        upvotes: 67,
        downvotes: 2,
        depth: 0,
        replies: [],
        createdAt: new Date('2026-01-14T10:45:00'),
    },
    {
        id: 'comment-3',
        postId: 'post-101',
        authorId: 'user-14',
        author: { ...mockUsers[4], fandomScore: 18 },
        content: 'Jealous! I only managed to get GA but still so excited! 🎉',
        upvotes: 34,
        downvotes: 0,
        depth: 0,
        replies: [
            {
                id: 'comment-3-1',
                postId: 'post-101',
                authorId: 'user-18',
                author: { ...mockUsers[8], fandomScore: 88 },
                content: 'GA is still amazing! Sometimes the energy in the pit is even better than VIP.',
                upvotes: 28,
                downvotes: 0,
                parentId: 'comment-3',
                depth: 1,
                replies: [],
                createdAt: new Date('2026-01-14T12:30:00'),
            },
        ],
        createdAt: new Date('2026-01-14T12:00:00'),
    },
];

export { mockUsers };
