import { Event, User, Ticket, ResaleListing } from "./types";

export const mockUser: User = {
  id: "user-1",
  email: "alex@example.com",
  name: "Alex Thompson",
  avatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&h=150&fit=crop",
  fandomScore: 78,
  spotifyConnected: true,
  walletAddress: "0x1234...5678",
  createdAt: new Date("2024-06-15"),
  eventsAttended: 12,
  vouchesGiven: 3,
  vouchesReceived: 5,
};

export const mockEvents: Event[] = [
  {
    id: "evt-1",
    title: "The Midnight Tour 2026",
    artist: "The Midnight",
    artistImage: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400&h=400&fit=crop",
    venue: "Madison Square Garden",
    location: "New York, NY",
    date: new Date("2026-03-15"),
    time: "8:00 PM",
    image: "https://images.unsplash.com/photo-1540039155733-5bb30b53aa14?w=800&h=400&fit=crop",
    description: "Experience the synthwave sensation live! The Midnight brings their iconic sound to MSG for one unforgettable night. Featuring songs from their latest album and classic hits that defined the genre.",
    category: "concert",
    ticketTiers: [
      {
        id: "tier-1",
        name: "General Admission",
        price: 0.012,
        currency: "USD",
        description: "Standing room on the floor",
        available: 245,
        total: 500,
        benefits: ["Floor access", "Digital collectible"],
      },
      {
        id: "tier-2",
        name: "VIP Experience",
        price: 249,
        currency: "USD",
        description: "Premium viewing area with perks",
        available: 48,
        total: 100,
        benefits: ["Premium viewing area", "Exclusive merch", "Early entry", "Meet & greet lottery"],
      },
      {
        id: "tier-3",
        name: "Ultimate Fan Package",
        price: 499,
        currency: "USD",
        description: "The complete experience",
        available: 5,
        total: 20,
        benefits: ["Front row reserved", "Backstage tour", "Signed poster", "Photo with artist", "All VIP benefits"],
      },
    ],
    totalTickets: 620,
    soldTickets: 322,
    resaleEnabled: true,
    resaleCap: 120,
    artistRoyalty: 10,
    status: "on-sale",
    minFandomScore: 40,
  },
  {
    id: "evt-2",
    title: "Electronic Dreams Festival",
    artist: "Various Artists",
    artistImage: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=400&h=400&fit=crop",
    venue: "Coachella Valley",
    location: "Indio, CA",
    date: new Date("2026-04-20"),
    time: "2:00 PM",
    image: "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=800&h=400&fit=crop",
    description: "Three days of non-stop electronic music featuring over 50 artists across 5 stages. Camp under the stars and dance until dawn.",
    category: "festival",
    ticketTiers: [
      {
        id: "tier-1",
        name: "3-Day Pass",
        price: 399,
        currency: "USD",
        description: "Full festival access",
        available: 1200,
        total: 5000,
        benefits: ["All stage access", "Festival grounds", "Digital collectible"],
      },
      {
        id: "tier-2",
        name: "3-Day VIP",
        price: 799,
        currency: "USD",
        description: "Enhanced festival experience",
        available: 180,
        total: 500,
        benefits: ["VIP viewing decks", "Air-conditioned lounges", "Premium food & drinks", "Private restrooms"],
      },
    ],
    totalTickets: 5500,
    soldTickets: 4120,
    resaleEnabled: true,
    resaleCap: 110,
    artistRoyalty: 5,
    status: "on-sale",
  },
  {
    id: "evt-3",
    title: "Lakers vs Celtics",
    artist: "LA Lakers",
    artistImage: "https://images.unsplash.com/photo-1546519638-68e109498ffc?w=400&h=400&fit=crop",
    venue: "Crypto.com Arena",
    location: "Los Angeles, CA",
    date: new Date("2026-02-28"),
    time: "7:30 PM",
    image: "https://images.unsplash.com/photo-1504450758481-7338bbe7524a?w=800&h=400&fit=crop",
    description: "The classic NBA rivalry continues! Watch the Lakers take on the Celtics in what promises to be an epic showdown.",
    category: "sports",
    ticketTiers: [
      {
        id: "tier-1",
        name: "Upper Level",
        price: 125,
        currency: "USD",
        description: "Sections 301-333",
        available: 890,
        total: 2000,
        benefits: ["Seat access", "Digital collectible"],
      },
      {
        id: "tier-2",
        name: "Lower Level",
        price: 350,
        currency: "USD",
        description: "Sections 101-119",
        available: 120,
        total: 800,
        benefits: ["Premium seating", "Club access"],
      },
      {
        id: "tier-3",
        name: "Courtside",
        price: 2500,
        currency: "USD",
        description: "First 3 rows",
        available: 4,
        total: 40,
        benefits: ["Courtside experience", "VIP parking", "Exclusive lounge", "Player meet opportunity"],
      },
    ],
    totalTickets: 2840,
    soldTickets: 1826,
    resaleEnabled: true,
    resaleCap: 150,
    artistRoyalty: 8,
    status: "on-sale",
  },
  {
    id: "evt-4",
    title: "Arctic Monkeys World Tour",
    artist: "Arctic Monkeys",
    artistImage: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=400&h=400&fit=crop",
    venue: "The O2 Arena",
    location: "London, UK",
    date: new Date("2026-05-10"),
    time: "7:00 PM",
    image: "https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=800&h=400&fit=crop",
    description: "The Sheffield legends return for their highly anticipated world tour. Featuring new material and beloved classics.",
    category: "concert",
    ticketTiers: [
      {
        id: "tier-1",
        name: "Standing",
        price: 95,
        currency: "GBP",
        description: "General admission standing",
        available: 0,
        total: 3000,
        benefits: ["Floor access", "Digital collectible"],
      },
      {
        id: "tier-2",
        name: "Seated",
        price: 85,
        currency: "GBP",
        description: "Tiered seating",
        available: 0,
        total: 2000,
        benefits: ["Reserved seat", "Digital collectible"],
      },
    ],
    totalTickets: 5000,
    soldTickets: 5000,
    resaleEnabled: true,
    resaleCap: 125,
    artistRoyalty: 12,
    status: "sold-out",
    minFandomScore: 60,
  },
  {
    id: "evt-5",
    title: "Taylor Swift | Eras Tour Extended",
    artist: "Taylor Swift",
    artistImage: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=400&h=400&fit=crop",
    venue: "SoFi Stadium",
    location: "Los Angeles, CA",
    date: new Date("2026-06-21"),
    time: "6:30 PM",
    image: "https://images.unsplash.com/photo-1429962714451-bb934ecdc4ec?w=800&h=400&fit=crop",
    description: "The phenomenon continues! Taylor Swift extends her record-breaking Eras Tour with new surprises and special guests.",
    category: "concert",
    ticketTiers: [
      {
        id: "tier-1",
        name: "General Admission",
        price: 199,
        currency: "USD",
        description: "Floor standing",
        available: 800,
        total: 4000,
        benefits: ["Floor access", "Commemorative wristband", "Digital collectible"],
      },
      {
        id: "tier-2",
        name: "Lower Bowl",
        price: 299,
        currency: "USD",
        description: "Premium seating sections",
        available: 450,
        total: 3000,
        benefits: ["Reserved seating", "Early merch access", "Digital collectible"],
      },
      {
        id: "tier-3",
        name: "Lover Experience",
        price: 899,
        currency: "USD",
        description: "Ultimate Swiftie package",
        available: 25,
        total: 200,
        benefits: ["Front section access", "Exclusive merch box", "Early entry", "Commemorative ticket"],
      },
    ],
    totalTickets: 7200,
    soldTickets: 5925,
    resaleEnabled: true,
    resaleCap: 100,
    artistRoyalty: 15,
    status: "on-sale",
    minFandomScore: 70,
  },
  {
    id: "evt-6",
    title: "Dave Chappelle Live",
    artist: "Dave Chappelle",
    artistImage: "https://images.unsplash.com/photo-1585699324551-f6c309eedeca?w=400&h=400&fit=crop",
    venue: "Radio City Music Hall",
    location: "New York, NY",
    date: new Date("2026-04-05"),
    time: "9:00 PM",
    image: "https://images.unsplash.com/photo-1527224538127-2104bb71c51b?w=800&h=400&fit=crop",
    description: "The comedy legend returns to Radio City for an intimate evening of stand-up. No phones allowed - be present for this special night.",
    category: "comedy",
    ticketTiers: [
      {
        id: "tier-1",
        name: "Orchestra",
        price: 175,
        currency: "USD",
        description: "Main floor seating",
        available: 340,
        total: 1200,
        benefits: ["Premium viewing", "Digital collectible"],
      },
      {
        id: "tier-2",
        name: "Mezzanine",
        price: 125,
        currency: "USD",
        description: "Balcony seating",
        available: 520,
        total: 800,
        benefits: ["Elevated view", "Digital collectible"],
      },
    ],
    totalTickets: 2000,
    soldTickets: 1140,
    resaleEnabled: false,
    artistRoyalty: 0,
    status: "on-sale",
  },
];

export const mockTickets: Ticket[] = [
  {
    id: "tkt-1",
    eventId: "evt-1",
    event: mockEvents[0],
    tierId: "tier-2",
    tierName: "VIP Experience",
    ownerId: "user-1",
    originalPrice: 249,
    currentPrice: 249,
    purchaseDate: new Date("2025-12-20"),
    status: "active",
    qrCode: "QR_CODE_DATA_1",
    tokenId: "12345",
    transactionHash: "0xabc...def",
  },
  {
    id: "tkt-2",
    eventId: "evt-3",
    event: mockEvents[2],
    tierId: "tier-2",
    tierName: "Lower Level",
    ownerId: "user-1",
    originalPrice: 350,
    currentPrice: 350,
    purchaseDate: new Date("2025-11-15"),
    status: "active",
    qrCode: "QR_CODE_DATA_2",
    tokenId: "12346",
    transactionHash: "0xdef...ghi",
  },
  {
    id: "tkt-3",
    eventId: "evt-6",
    event: mockEvents[5],
    tierId: "tier-1",
    tierName: "Orchestra",
    ownerId: "user-1",
    originalPrice: 175,
    currentPrice: 175,
    purchaseDate: new Date("2026-01-05"),
    status: "active",
    qrCode: "QR_CODE_DATA_3",
    tokenId: "12347",
    transactionHash: "0xghi...jkl",
  },
];

export const mockResaleListings: ResaleListing[] = [
  {
    id: "resale-1",
    ticketId: "tkt-external-1",
    ticket: {
      ...mockTickets[0],
      id: "tkt-external-1",
      event: mockEvents[3],
      tierName: "Standing",
      originalPrice: 95,
      currentPrice: 115,
    },
    sellerId: "user-external-1",
    price: 115,
    listedAt: new Date("2026-01-08"),
    status: "active",
  },
  {
    id: "resale-2",
    ticketId: "tkt-external-2",
    ticket: {
      ...mockTickets[0],
      id: "tkt-external-2",
      event: mockEvents[4],
      tierName: "General Admission",
      originalPrice: 199,
      currentPrice: 199,
    },
    sellerId: "user-external-2",
    price: 199,
    listedAt: new Date("2026-01-10"),
    status: "active",
  },
  {
    id: "resale-3",
    ticketId: "tkt-external-3",
    ticket: {
      ...mockTickets[0],
      id: "tkt-external-3",
      event: mockEvents[0],
      tierName: "VIP Experience",
      originalPrice: 249,
      currentPrice: 289,
    },
    sellerId: "user-external-3",
    price: 289,
    listedAt: new Date("2026-01-12"),
    status: "active",
  },
  {
    id: "resale-4",
    ticketId: "tkt-external-4",
    ticket: {
      ...mockTickets[0],
      id: "tkt-external-4",
      event: mockEvents[2],
      tierName: "Lower Level",
      originalPrice: 350,
      currentPrice: 420,
    },
    sellerId: "user-external-4",
    price: 420,
    listedAt: new Date("2026-01-11"),
    status: "active",
  },
  {
    id: "resale-5",
    ticketId: "tkt-external-5",
    ticket: {
      ...mockTickets[0],
      id: "tkt-external-5",
      event: mockEvents[4],
      tierName: "Lower Bowl",
      originalPrice: 299,
      currentPrice: 299,
    },
    sellerId: "user-external-5",
    price: 299,
    listedAt: new Date("2026-01-09"),
    status: "active",
  },
  {
    id: "resale-6",
    ticketId: "tkt-external-6",
    ticket: {
      ...mockTickets[0],
      id: "tkt-external-6",
      event: mockEvents[1],
      tierName: "3-Day Pass",
      originalPrice: 399,
      currentPrice: 435,
    },
    sellerId: "user-external-6",
    price: 435,
    listedAt: new Date("2026-01-07"),
    status: "active",
  },
];

export const featuredArtists = [
  { name: "The Midnight", image: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=200&h=200&fit=crop", genre: "Synthwave" },
  { name: "Arctic Monkeys", image: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=200&h=200&fit=crop", genre: "Rock" },
  { name: "Taylor Swift", image: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=200&h=200&fit=crop", genre: "Pop" },
  { name: "Kendrick Lamar", image: "https://images.unsplash.com/photo-1499364615650-ec38552f4f34?w=200&h=200&fit=crop", genre: "Hip-Hop" },
  { name: "Daft Punk", image: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=200&h=200&fit=crop", genre: "Electronic" },
  { name: "Beyoncé", image: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop", genre: "R&B" },
];

export const categories = [
  { id: "concert", name: "Concerts", icon: "🎵", count: 156, image: "https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=800&h=800&fit=crop" },
  { id: "festival", name: "Festivals", icon: "🎪", count: 23, image: "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=800&h=800&fit=crop" },
  { id: "sports", name: "Sports", icon: "🏀", count: 89, image: "https://images.unsplash.com/photo-1504450758481-7338bbe7524a?w=800&h=800&fit=crop" },
  { id: "theater", name: "Theater", icon: "🎭", count: 45, image: "https://images.unsplash.com/photo-1503095396549-807039045349?w=800&h=800&fit=crop" },
  { id: "comedy", name: "Comedy", icon: "😂", count: 34, image: "https://images.unsplash.com/photo-1527224538127-2104bb71c51b?w=800&h=800&fit=crop" },
];

// Community Mock Data
import type { Community, CommunityPost, GovernanceProposal, CommunityMember } from "./types";

export const mockCommunities: Community[] = [
  {
    id: "community-1",
    name: "Swifties United",
    artistId: "artist-1",
    artistName: "Taylor Swift",
    artistImage: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=400&h=400&fit=crop",
    description: "Official Taylor Swift fan community. Vote on setlist requests, Eras Tour meetups, exclusive merchandise drops, and connect with Swifties worldwide.",
    memberCount: 89432,
    tokenMintAddress: "5ZiE3vAkrdXBgyFL7KqG3RoEGBws4CjRcXVbABDLUIbM",
    accessRequirement: {
      type: "token",
      minAmount: 100,
    },
    governance: {
      proposalCount: 156,
      votingPower: "token",
    },
    createdAt: new Date("2025-06-01"),
    isActive: true,
  },
  {
    id: "community-2",
    name: "ARMY Global",
    artistId: "artist-2",
    artistName: "BTS",
    artistImage: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=400&h=400&fit=crop",
    description: "Join BTS ARMY! Participate in comeback voting, exclusive content access, fan projects, and connect with fellow members globally.",
    memberCount: 124567,
    nftCollectionAddress: "8HdGR9pZbKYxqNXEJYdKE3Qp9MxNNZXJZBFH94q6YqCX",
    accessRequirement: {
      type: "nft",
    },
    governance: {
      proposalCount: 234,
      votingPower: "reputation",
    },
    createdAt: new Date("2025-04-12"),
    isActive: true,
  },
  {
    id: "community-3",
    name: "Beyhive",
    artistId: "beyonce",
    artistName: "Beyoncé",
    artistImage: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400&h=400&fit=crop",
    description: "Official Beyoncé fan community. Get early access to Renaissance Tour dates, exclusive merch voting, and connect with the Beyhive worldwide.",
    memberCount: 95238,
    accessRequirement: {
      type: "fandom-score",
      minScore: 60,
    },
    governance: {
      proposalCount: 89,
      votingPower: "equal",
    },
    createdAt: new Date("2025-08-20"),
    isActive: true,
  },
  {
    id: "community-4",
    name: "Arianators",
    artistId: "ariana",
    artistName: "Ariana Grande",
    artistImage: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=400&h=400&fit=crop",
    description: "Ariana Grande's official community. Vote on album artwork, tour setlists, and exclusive behind-the-scenes content access.",
    memberCount: 67891,
    tokenMintAddress: "9XdGR8pZbKYxqNXEJYdKE3Qp9MxNNZXJZBFH94q7ZrDY",
    accessRequirement: {
      type: "token",
      minAmount: 50,
    },
    governance: {
      proposalCount: 67,
      votingPower: "token",
    },
    createdAt: new Date("2025-07-15"),
    isActive: true,
  },
  {
    id: "community-5",
    name: "OVO Sound",
    artistId: "drake",
    artistName: "Drake",
    artistImage: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=400&h=400&fit=crop",
    description: "Drake's OVO Sound community. Access exclusive drops, vote on tour cities, special merchandise, and connect with OVO fans globally.",
    memberCount: 56782,
    nftCollectionAddress: "7FcHR8pZbKYxqNXEJYdKE3Qp9MxNNZXJZBFH94q8YsTZ",
    accessRequirement: {
      type: "nft",
    },
    governance: {
      proposalCount: 92,
      votingPower: "reputation",
    },
    createdAt: new Date("2025-09-01"),
    isActive: true,
  },
  {
    id: "community-6",
    name: "The Weeknd XO",
    artistId: "weeknd",
    artistName: "The Weeknd",
    artistImage: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=400&h=400&fit=crop",
    description: "XO Crew! Join The Weeknd's official community for exclusive tour announcements, merch voting, and special Dawn FM events.",
    memberCount: 48923,
    accessRequirement: {
      type: "fandom-score",
      minScore: 50,
    },
    governance: {
      proposalCount: 54,
      votingPower: "equal",
    },
    createdAt: new Date("2025-10-12"),
    isActive: true,
  },
];

export const mockCommunityPosts: CommunityPost[] = [
  {
    id: "post-1",
    communityId: "community-1",
    authorId: "user-1",
    author: mockUser,
    title: "Madison Square Garden Meetup",
    content: "Can't wait for the MSG show! Anyone else going? Let's meet up before! 🌆✨",
    type: "discussion",
    upvotes: 234,
    downvotes: 12,
    commentCount: 45,
    isPinned: false,
    createdAt: new Date("2026-01-10T14:30:00"),
    updatedAt: new Date("2026-01-10T14:30:00"),
  },
  {
    id: "post-2",
    communityId: "community-1",
    authorId: "user-2",
    author: {
      ...mockUser,
      id: "user-2",
      name: "Sarah Martinez",
      avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&h=150&fit=crop",
    },
    title: "New POAP Badge",
    content: "Just minted my POAP from the last show! The badge looks amazing 🎵",
    type: "photo",
    images: ["https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&h=400&fit=crop"],
    upvotes: 567,
    downvotes: 4,
    commentCount: 89,
    isPinned: true,
    createdAt: new Date("2026-01-09T10:15:00"),
    updatedAt: new Date("2026-01-09T10:15:00"),
  },
];

export const mockProposals: GovernanceProposal[] = [
  {
    id: "proposal-1",
    communityId: "community-1",
    proposerId: "user-1",
    proposer: mockUser,
    title: "Add 'Sunset' to MSG Setlist",
    description: "Vote to add the fan-favorite track 'Sunset' to the upcoming Madison Square Garden show. This would replace one of the current songs in the second half of the set.",
    type: "setlist-vote",
    options: [
      { id: "opt-1", text: "Yes, add Sunset", votes: 8234, percentage: 68.5 },
      { id: "opt-2", text: "No, keep current setlist", votes: 3789, percentage: 31.5 },
    ],
    startDate: new Date("2026-01-08"),
    endDate: new Date("2026-01-15"),
    status: "active",
    quorumRequired: 5000,
    totalVotes: 12023,
    onChainProposalId: "3NZ8VHkXYZ9Xh5QKfJ9X8YqT7W6VU5sT4R3PQ2nM1kL8",
  },
  {
    id: "proposal-2",
    communityId: "community-1",
    proposerId: "user-3",
    proposer: {
      ...mockUser,
      id: "user-3",
      name: "Mike Chen",
    },
    title: "New Merch Design Vote",
    description: "Choose the design for the exclusive community hoodie. The winning design will be available for pre-order next week.",
    type: "merch-design",
    options: [
      { id: "opt-1", text: "Retro Wave Design", votes: 4521, percentage: 45.2 },
      { id: "opt-2", text: "Neon City Skyline", votes: 3892, percentage: 38.9 },
      { id: "opt-3", text: "Abstract Synth Pattern", votes: 1587, percentage: 15.9 },
    ],
    startDate: new Date("2026-01-05"),
    endDate: new Date("2026-01-20"),
    status: "active",
    quorumRequired: 3000,
    totalVotes: 10000,
    onChainProposalId: "7KpQ9MxR4VnE2YhT8WjF5xK3PdL6VsW9uB1NA7cM2gH5",
  },
  {
    id: "proposal-3",
    communityId: "community-2",
    proposerId: "user-4",
    proposer: {
      ...mockUser,
      id: "user-4",
      name: "Emma Wilson",
    },
    title: "EU Tour Date Preference",
    description: "Help us decide which European cities to prioritize for the next tour!",
    type: "event-date",
    options: [
      { id: "opt-1", text: "London", votes: 5632, percentage: 32.1 },
      { id: "opt-2", text: "Berlin", votes: 4891, percentage: 27.9 },
      { id: "opt-3", text: "Paris", votes: 3456, percentage: 19.7 },
      { id: "opt-4", text: "Amsterdam", votes: 3571, percentage: 20.3 },
    ],
    startDate: new Date("2026-01-01"),
    endDate: new Date("2026-01-08"),
    status: "passed",
    quorumRequired: 8000,
    totalVotes: 17550,
    onChainProposalId: "9QxW2TnV5KpM8HrF3YjL6xP4RdE7VgN1uS9OB3mC4aG7",
  },
];

