# RAG Vector Store with ChromaDB
# Stores FanFirst knowledge base for semantic search

import chromadb
from chromadb.utils import embedding_functions
import os

# FanFirst Knowledge Base Documents
KNOWLEDGE_BASE = [
    # About FanFirst
    {
        "id": "about_1",
        "content": """FanFirst is an AI-powered NFT ticketing platform that ensures real fans get access to tickets before scalpers and bots. 
        We use blockchain technology, fan verification quizzes, and community vouching to create a fair ticketing ecosystem.
        Founded to solve the scalping problem that has plagued concert and event ticketing for decades.""",
        "category": "about",
        "keywords": ["fanfirst", "about", "what is", "company", "platform"]
    },
    {
        "id": "about_2",
        "content": """FanFirst is different from Ticketmaster because we prioritize real fans over profit. 
        Our FanIQ Quiz verifies you're a genuine fan before purchase. We cap resale prices to prevent scalping.
        Artists get royalties on every resale. Everything is transparent on the blockchain.""",
        "category": "about",
        "keywords": ["ticketmaster", "different", "compare", "vs", "better"]
    },
    
    # NFT Tickets
    {
        "id": "nft_1",
        "content": """NFT tickets are blockchain-based digital tickets that can't be counterfeited. 
        They're stored in your crypto wallet (MetaMask, Phantom, etc.) and give you true ownership.
        Benefits include: proof of attendance, collectible value, secure transfer, and transparent history.""",
        "category": "nft",
        "keywords": ["nft", "blockchain", "ticket", "digital", "crypto"]
    },
    {
        "id": "nft_2", 
        "content": """Your NFT ticket is minted on Polygon blockchain, which has low gas fees and is environmentally friendly.
        The ticket contains: event details, seat information, QR code for entry, and unique artwork.
        After the event, your ticket becomes a collectible proof of attendance.""",
        "category": "nft",
        "keywords": ["polygon", "mint", "gas", "blockchain", "collectible"]
    },
    
    # FanIQ Quiz
    {
        "id": "quiz_1",
        "content": """The FanIQ Quiz is our anti-bot verification system. Before purchasing tickets, you answer questions about the artist.
        Real fans pass easily. Bots and scalpers fail. This ensures tickets go to genuine fans.
        Quiz questions are generated by AI based on the artist's history, songs, and trivia.""",
        "category": "quiz",
        "keywords": ["quiz", "faniq", "verification", "anti-bot", "questions"]
    },
    {
        "id": "quiz_2",
        "content": """Quiz scoring is based on correctness, speed, and consistency. Higher scores boost your Fandom Score.
        You get 5 questions per quiz. Each question has 15 seconds to answer.
        Passing the quiz is required before you can purchase tickets for that event.""",
        "category": "quiz", 
        "keywords": ["score", "points", "pass", "fail", "time"]
    },
    
    # Fandom Score
    {
        "id": "fandom_1",
        "content": """Fandom Score measures your engagement as a fan on FanFirst. Higher scores unlock benefits like early ticket access.
        Earn points by: attending events (+50), community participation (+10), quiz completion (+5-25), getting vouched (+15).
        Your score is visible on your profile and to event organizers.""",
        "category": "fandom",
        "keywords": ["fandom", "score", "points", "earn", "benefits"]
    },
    
    # Tickets & Purchasing
    {
        "id": "purchase_1",
        "content": """To buy tickets: 1) Browse events at /events 2) Select your event 3) Complete FanIQ Quiz 
        4) Connect your crypto wallet 5) Purchase with crypto or card 6) NFT ticket minted to your wallet.
        Supported wallets: MetaMask, Phantom, Coinbase Wallet, WalletConnect compatible.""",
        "category": "purchase",
        "keywords": ["buy", "purchase", "how to", "wallet", "payment"]
    },
    {
        "id": "purchase_2",
        "content": """We accept payment via cryptocurrency (ETH, MATIC, SOL) and credit/debit cards.
        Card payments are processed through Stripe and automatically converted to crypto for minting.
        Gas fees on Polygon are typically under $0.01 per transaction.""",
        "category": "purchase",
        "keywords": ["payment", "card", "crypto", "stripe", "gas"]
    },
    
    # Refunds
    {
        "id": "refund_1",
        "content": """Refund policy: Full refunds if event is cancelled. Option to refund or keep ticket if postponed.
        Self-cancellation available within 48 hours of purchase minus gas fees.
        To request refund: Dashboard → My Tickets → Select ticket → Request Refund.""",
        "category": "refund",
        "keywords": ["refund", "cancel", "money back", "return"]
    },
    
    # Resale
    {
        "id": "resale_1",
        "content": """Resale is allowed but capped to prevent scalping. Maximum markup is typically 120% of original price.
        Artists receive 10% royalty on every resale transaction. This benefits creators and prevents exploitation.
        To list for resale: Dashboard → My Tickets → List for Sale → Set price (within cap).""",
        "category": "resale",
        "keywords": ["resale", "sell", "resell", "scalp", "markup"]
    },
    
    # Security & Privacy
    {
        "id": "security_1",
        "content": """Your data is secure on FanFirst. We use Auth0 for authentication, encrypted connections, and blockchain for transparency.
        We don't sell your data. Spotify integration only reads your following list, not listening history.
        Wallet connections are non-custodial - we never have access to your private keys or funds.""",
        "category": "security",
        "keywords": ["security", "privacy", "data", "safe", "secure"]
    },
    
    # Wallet
    {
        "id": "wallet_1",
        "content": """To connect your wallet: Click 'Connect Wallet' in the header. Choose MetaMask (EVM) or Phantom (Solana).
        Approve the connection in your wallet. Your wallet address is now linked to your account.
        You need a connected wallet to purchase and receive NFT tickets.""",
        "category": "wallet",
        "keywords": ["wallet", "metamask", "phantom", "connect", "address"]
    },
    
    # Events
    {
        "id": "events_1",
        "content": """Upcoming events on FanFirst: Lakers games at Crypto.com Arena, Taylor Swift Eras Tour at SoFi Stadium,
        Drake concert at Staples Center, Hamilton Broadway Tour at Dolby Theatre.
        Browse all events at /events. Filter by category, date, or artist.""",
        "category": "events",
        "keywords": ["events", "concerts", "games", "shows", "upcoming"]
    },
    
    # Support
    {
        "id": "support_1",
        "content": """Need help? Contact us at support@fanfirst.com or use this chat support.
        For urgent issues, email with subject 'URGENT' for priority response within 2 hours.
        Check our FAQ at /faq for common questions.""",
        "category": "support",
        "keywords": ["help", "support", "contact", "email", "issue"]
    },
]


class VectorStore:
    """ChromaDB vector store for RAG"""
    
    def __init__(self):
        # Use sentence-transformers for embeddings (free, local)
        self.embedding_fn = embedding_functions.SentenceTransformerEmbeddingFunction(
            model_name="all-MiniLM-L6-v2"  # Fast, good quality
        )
        
        # In-memory ChromaDB
        self.client = chromadb.Client()
        
        # Create collection
        self.collection = self.client.get_or_create_collection(
            name="fanfirst_knowledge",
            embedding_function=self.embedding_fn,
            metadata={"description": "FanFirst support knowledge base"}
        )
        
        # Load knowledge base
        self._load_knowledge_base()
        print(f"[RAG] Loaded {self.collection.count()} documents into vector store")
    
    def _load_knowledge_base(self):
        """Load all documents into ChromaDB"""
        if self.collection.count() > 0:
            return  # Already loaded
        
        ids = [doc["id"] for doc in KNOWLEDGE_BASE]
        documents = [doc["content"] for doc in KNOWLEDGE_BASE]
        metadatas = [{"category": doc["category"], "keywords": ",".join(doc["keywords"])} for doc in KNOWLEDGE_BASE]
        
        self.collection.add(
            ids=ids,
            documents=documents,
            metadatas=metadatas
        )
    
    def search(self, query: str, n_results: int = 3) -> list[dict]:
        """Search for relevant documents"""
        results = self.collection.query(
            query_texts=[query],
            n_results=n_results,
            include=["documents", "metadatas", "distances"]
        )
        
        docs = []
        if results and results["documents"]:
            for i, doc in enumerate(results["documents"][0]):
                docs.append({
                    "content": doc,
                    "category": results["metadatas"][0][i]["category"],
                    "distance": results["distances"][0][i] if results["distances"] else 0
                })
        
        return docs
    
    def get_context(self, query: str, max_tokens: int = 1000) -> str:
        """Get formatted context for LLM"""
        docs = self.search(query, n_results=3)
        
        if not docs:
            return ""
        
        context_parts = []
        for doc in docs:
            # Only include if reasonably relevant (distance < 1.5)
            if doc["distance"] < 1.5:
                context_parts.append(f"[{doc['category'].upper()}]: {doc['content']}")
        
        return "\n\n".join(context_parts)[:max_tokens]


# Global instance
_vector_store = None

def get_vector_store() -> VectorStore:
    """Get or create vector store singleton"""
    global _vector_store
    if _vector_store is None:
        _vector_store = VectorStore()
    return _vector_store
